- name : Configure Docker, containerize, and deploy Banking Application in Test server
  hosts : all
  become: true
  connection : ssh
  tasks : 
  - name: Package update
    command : sudo apt-get update

  - name : Install Docker
    command : sudo apt-get install -y docker.io

  - name : Start Docker Service
    command : sudo systemctl start docker

  - name: Deploy Docker Container
    command: docker run -itd --name CBS -p 8084:8081 pradocks/cbs:v1
